#!/bin/bash

set -e

case "$1" in
    purge|remove)
        if [ "$1" = "purge" ]; then
            userdel testing-task 2>/dev/null || true
            groupdel testing-task 2>/dev/null || true
        fi

        systemctl daemon-reload || true
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0